--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "PUBLIC"."TRADER" DROP CONSTRAINT "SYS_REF_SYS_FK_155_157";

ALTER TABLE "PUBLIC"."TRADER" DROP CONSTRAINT "SYS_PK_117";

ALTER TABLE "PUBLIC"."TRADER" DROP CONSTRAINT "SYS_REF_SYS_FK_126_148";

DROP INDEX "PUBLIC"."SYS_IDX_116";

DROP TABLE "PUBLIC"."TRADER";

CREATE TABLE "PUBLIC"."TRADER" (
		"ID" INTEGER NOT NULL,
		"NAME" VARCHAR(2147483647),
		"EMAIL" VARCHAR(250),
		"GOOGLEUSERID" VARCHAR(250),
		"CANADMIN" BOOLEAN
	);

CREATE UNIQUE INDEX "PUBLIC"."SYS_IDX_116" ON "PUBLIC"."TRADER" ("ID" ASC);

ALTER TABLE "PUBLIC"."TRADER" ADD CONSTRAINT "SYS_REF_SYS_FK_155_157" UNIQUE ("ID");

ALTER TABLE "PUBLIC"."TRADER" ADD CONSTRAINT "SYS_PK_117" PRIMARY KEY ("ID");

ALTER TABLE "PUBLIC"."TRADER" ADD CONSTRAINT "SYS_REF_SYS_FK_126_148" UNIQUE ("ID");

