package traderjournal.model.entities;

// Generated 2009/09/11 03:55:57 by Hibernate Tools 3.2.5.Beta

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

import traderjournal.model.RequestFactoryUtilsJpa;

/**
 * Account generated by hbm2java
 */
@Entity
public class Account implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id = -1;
	
	@ManyToOne
	@JoinColumn(name="base_ccy_id")
	private Ccy ccy; 
	
	@ManyToOne
	private Trader trader;
	
	
	private String name;
	private double balance;
	@Column(name="percent_risk")
	private Double percentRisk;
	@OneToMany(mappedBy="account", fetch=FetchType.LAZY, cascade = {CascadeType.PERSIST,CascadeType.MERGE }) 
	private List<Trade> trades = new ArrayList<Trade>();


	public Trader getTrader() {
		return trader;
	}


	public void setTrader(Trader trader) {
		this.trader = trader;
	}

	
	public Account() {
	}

	public Account(int id, Ccy ccy, String name, double balance) {
		this.id = id;
		this.ccy = ccy;
		this.name = name;
		this.balance = balance;
	}

	public Account(int id, Ccy ccy, String name, double balance,
			Double percentRisk, List<Trade> trades) {
		this.id = id;
		this.ccy = ccy;
		this.name = name;
		this.balance = balance;
		this.percentRisk = percentRisk;
		this.trades = trades;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Ccy getCcy() {
		return this.ccy;
	}

	public void setCcy(Ccy ccy) {
		this.ccy = ccy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getBalance() {
		return this.balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public Double getPercentRisk() {
		return this.percentRisk;
	}

	public void setPercentRisk(Double percentRisk) {
		this.percentRisk = percentRisk;
	}

	public List<Trade> getTrades() {
		return this.trades;
	}

	public void setTrades(List<Trade> trades) {
		this.trades = trades;
	}

	
	public static Long countAccount(){
		Account ac =  RequestFactoryUtilsJpa.find(Account.class, 1L);
		return new Long(ac.getTrades().size());
		
		
	}
	
	public static List<Account> findAllAccounts(){
		
		List<Account> accounts = RequestFactoryUtilsJpa.findAll(Account.class);
		return accounts;
		
		
	}
	
	public Integer getVersion(){
		return 0;
	}


	public static List<Account> findAll() {
		
		return RequestFactoryUtilsJpa.findAll(Account.class);
	}
	
}
