package traderjournal.wap.model.entities;

import java.util.ArrayList;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Ccy generated by hbm2java
 */
@Entity
public class Ccy implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private String name;

	@OneToMany(mappedBy="ccy", fetch=FetchType.LAZY, cascade = CascadeType.ALL) 
	private List<Account> accounts = new ArrayList<Account>();
	@OneToMany(mappedBy="ccy", fetch=FetchType.LAZY, cascade = CascadeType.ALL) 
	private List<Instrument> instruments = new ArrayList<Instrument>();
	public Ccy() {
	}

	public Ccy(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Ccy(int id, String name, List<Account> accounts, List<Instrument> instruments) {
		this.id = id;
		this.name = name;
		this.accounts = accounts;
		this.instruments = instruments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public List<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(List<Account> accounts) {
		this.accounts = accounts;
	}

	public List<Instrument> getInstruments() {
		return this.instruments;
	}

	public void setInstruments(List<Instrument> instruments) {
		this.instruments = instruments;
	}

	
	
	public Integer getVersion(){
		return 0;
	}
}
