package traderjournal.wap.model.entities;

// 

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Trader generated by hbm2java
 */
@Entity
public class Trader implements java.io.Serializable {
	private static final Logger log = Logger.getLogger(Trader.class.getName());
	
	
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	private String name;
	private String email;
	private String googleuserid;
	private boolean canadmin;
	
	@OneToMany(mappedBy="trader", fetch=FetchType.LAZY, cascade = CascadeType.ALL) 
	private List<Account> accounts = new ArrayList<Account>();
	
	
	
	public List<Account> getAccounts() {
		return accounts;
	}

	public void setAccounts(List<Account> accounts) {
		this.accounts = accounts;
	}

	public String getGoogleuserid() {
		return googleuserid;
	}

	public void setGoogleuserid(String googleuserid) {
		this.googleuserid = googleuserid;
	}

	public boolean getcanadmin() {
		return canadmin;
	}

	public void setCanadmin(boolean canadmin) {
		this.canadmin = canadmin;
	}



	public Trader() {
	}

	public Trader(Long id) {
		this.id = id;
	}

	public Trader(Long id, String name) {
	this.id = id;
		this.name = name;

	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	
	

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	
		  
	
}
