package traderjournal.model.entities;

// Generated 2009/09/11 03:55:57 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Account generated by hbm2java
 */
@Entity
public class Account implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private int id;
	private Ccy ccy;
	
	
	private String name;
	private double balance;
	private Double percentRisk;
	private Set trades = new HashSet(0);

	public static List<Account> findAllAccounts(){
		
		
		
		return null;
		
		
	}
	
	
	public Account() {
	}

	public Account(int id, Ccy ccy, String name, double balance) {
		this.id = id;
		this.ccy = ccy;
		this.name = name;
		this.balance = balance;
	}

	public Account(int id, Ccy ccy, String name, double balance,
			Double percentRisk, Set trades) {
		this.id = id;
		this.ccy = ccy;
		this.name = name;
		this.balance = balance;
		this.percentRisk = percentRisk;
		this.trades = trades;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Ccy getCcy() {
		return this.ccy;
	}

	public void setCcy(Ccy ccy) {
		this.ccy = ccy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getBalance() {
		return this.balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public Double getPercentRisk() {
		return this.percentRisk;
	}

	public void setPercentRisk(Double percentRisk) {
		this.percentRisk = percentRisk;
	}

	public Set getTrades() {
		return this.trades;
	}

	public void setTrades(Set trades) {
		this.trades = trades;
	}

}
