package traderjournal.model.hibernate;

// Generated 2008/05/26 04:30:45 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Ccy generated by hbm2java
 */
public class Ccy implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Account> accounts = new HashSet<Account>(0);

	public Ccy() {
	}

	public Ccy(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Ccy(int id, String name, Set<Account> accounts) {
		this.id = id;
		this.name = name;
		this.accounts = accounts;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Account> getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set<Account> accounts) {
		this.accounts = accounts;
	}

}
