package traderjournal.model.hibernate;

// Generated 2009/09/11 03:55:57 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * Ccy generated by hbm2java
 */
public class Ccy implements java.io.Serializable {

	private int id;
	private String name;
	private Set accounts = new HashSet(0);
	private Set instruments = new HashSet(0);

	public Ccy() {
	}

	public Ccy(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public Ccy(int id, String name, Set accounts, Set instruments) {
		this.id = id;
		this.name = name;
		this.accounts = accounts;
		this.instruments = instruments;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public Set getInstruments() {
		return this.instruments;
	}

	public void setInstruments(Set instruments) {
		this.instruments = instruments;
	}

}
