package traderjournal.model.hibernate;

// Generated 2008/06/12 11:43:13 by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Trader generated by hbm2java
 */
public class Trader extends net.sf.hibernate4gwt.pojo.gwt.LazyGwtPojo implements
		java.io.Serializable {

	private int id;
	private String name;
	private Set<Trade> trades = new HashSet<Trade>(0);

	public Trader() {
	}

	public Trader(int id) {
		this.id = id;
	}

	public Trader(int id, String name, Set<Trade> trades) {
		this.id = id;
		this.name = name;
		this.trades = trades;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Trade> getTrades() {
		return this.trades;
	}

	public void setTrades(Set<Trade> trades) {
		this.trades = trades;
	}

}
