package traderjournal.model.hibernate;

// Generated 2008/05/26 04:30:45 by Hibernate Tools 3.2.1.GA

/**
 * Tradeeventimage generated by hbm2java
 */
public class Tradeeventimage implements java.io.Serializable {

	private TradeeventimageId id;
	private Tradeevent tradeevent;

	public Tradeeventimage() {
	}

	public Tradeeventimage(TradeeventimageId id) {
		this.id = id;
	}

	public Tradeeventimage(TradeeventimageId id, Tradeevent tradeevent) {
		this.id = id;
		this.tradeevent = tradeevent;
	}

	public TradeeventimageId getId() {
		return this.id;
	}

	public void setId(TradeeventimageId id) {
		this.id = id;
	}

	public Tradeevent getTradeevent() {
		return this.tradeevent;
	}

	public void setTradeevent(Tradeevent tradeevent) {
		this.tradeevent = tradeevent;
	}

}
