package traderjournal.model.hibernate;

// Generated 2009/09/11 03:55:57 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * Trader generated by hbm2java
 */
public class Trader implements java.io.Serializable {

	private int id;
	private String name;
	private Set trades = new HashSet(0);

	public Trader() {
	}

	public Trader(int id) {
		this.id = id;
	}

	public Trader(int id, String name, Set trades) {
		this.id = id;
		this.name = name;
		this.trades = trades;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTrades() {
		return this.trades;
	}

	public void setTrades(Set trades) {
		this.trades = trades;
	}

}
