package traderjournal.model.hibernate;

// Generated 2008/05/26 04:30:45 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Tradeeventtype generated by hbm2java
 */
public class Tradeeventtype implements java.io.Serializable {

	private int id;
	private String name;
	private Set<Tradeevent> tradeevents = new HashSet<Tradeevent>(0);

	public Tradeeventtype() {
	}

	public Tradeeventtype(int id) {
		this.id = id;
	}

	public Tradeeventtype(int id, String name, Set<Tradeevent> tradeevents) {
		this.id = id;
		this.name = name;
		this.tradeevents = tradeevents;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Tradeevent> getTradeevents() {
		return this.tradeevents;
	}

	public void setTradeevents(Set<Tradeevent> tradeevents) {
		this.tradeevents = tradeevents;
	}

}
