package traderjournal.model.hibernate;
// Generated 2009/01/29 04:30:34 by Hibernate Tools 3.2.4.CR1


import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Transaction generated by hbm2java
 */
public class Transaction  extends traderjournal.model.hibernate.HibernateBaseModel implements java.io.Serializable {


     private Integer id;
     private TransactionType transactionType;
     private Double transactionValue;

    public Transaction() {
    }

    public Transaction(TransactionType transactionType, Double transactionValue) {
       this.transactionType = transactionType;
       this.transactionValue = transactionValue;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TransactionType getTransactionType() {
        return this.transactionType;
    }
    
    public void setTransactionType(TransactionType transactionType) {
        this.transactionType = transactionType;
    }
    public Double getTransactionValue() {
        return this.transactionValue;
    }
    
    public void setTransactionValue(Double transactionValue) {
        this.transactionValue = transactionValue;
    }





public <X> X get(String property){
    if(property.equals("id")){

     return (X) getId(); 
    }
    if(property.equals("transactionType")){

     return (X) getTransactionType(); 
    }
    if(property.equals("transactionValue")){

     return (X) getTransactionValue(); 
    }
	return null;
}

public Map<String, Object> getProperties() {
		HashMap< String, Object> hm = new HashMap<String, Object>();
		
	    hm.put("id",getId() );
		
	    hm.put("transactionType",getTransactionType() );
		
	    hm.put("transactionValue",getTransactionValue() );
		return hm;
}

public Collection<String> getPropertyNames() {
		List<String> ret = new ArrayList<String>();
	    ret.add("id");
	    ret.add("transactionType");
	    ret.add("transactionValue");
		return ret;
	}


	public <X> X remove(String property) {
		// TODO Auto-generated method stub
		return null;
	}


	public <X> X set(String property, X value) {
		    if(property.equals("id")){
		     setId(( Integer)value) ; 
		    }
		    if(property.equals("transactionType")){
		     setTransactionType(( TransactionType)value) ; 
		    }
		    if(property.equals("transactionValue")){
		     setTransactionValue(( Double)value) ; 
		    }
		
		return null;
	}


}


