package traderjournal.model.entities;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

// Generated 2009/09/11 03:55:57 by Hibernate Tools 3.2.5.Beta

/**
 * Transaction generated by hbm2java
 */
@Entity
public class Transaction implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id = -1;
	private TransactionType transactionType;
	private double transactionValue;

	public Transaction() {
	}

	public Transaction(int id, TransactionType transactionType,
			double transactionValue) {
		this.id = id;
		this.transactionType = transactionType;
		this.transactionValue = transactionValue;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public TransactionType getTransactionType() {
		return this.transactionType;
	}

	public void setTransactionType(TransactionType transactionType) {
		this.transactionType = transactionType;
	}

	public double getTransactionValue() {
		return this.transactionValue;
	}

	public void setTransactionValue(double transactionValue) {
		this.transactionValue = transactionValue;
	}

}
