package traderjournal.model.entities;

// Generated 2009/09/11 03:55:57 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

/**
 * Tradeeventtype generated by hbm2java
 */
public class Tradeeventtype implements java.io.Serializable {

	private int id;
	private String name;
	private Set tradeevents = new HashSet(0);

	public Tradeeventtype() {
	}

	public Tradeeventtype(int id) {
		this.id = id;
	}

	public Tradeeventtype(int id, String name, Set tradeevents) {
		this.id = id;
		this.name = name;
		this.tradeevents = tradeevents;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTradeevents() {
		return this.tradeevents;
	}

	public void setTradeevents(Set tradeevents) {
		this.tradeevents = tradeevents;
	}

}
