package traderjournal.model.entities;

// 

import java.util.HashSet;
import java.util.Set;
import java.util.logging.Logger;

/**
 * Trader generated by hbm2java
 */
public class Trader implements java.io.Serializable {
	private static final Logger log = Logger.getLogger(Trader.class.getName());
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	
	private Integer id;
	private String name;
	private String email;
	public String getGoogleuserid() {
		return googleuserid;
	}

	public void setGoogleuserid(String googleuserid) {
		this.googleuserid = googleuserid;
	}

	public boolean getcanadmin() {
		return canadmin;
	}

	public void setCanadmin(boolean canadmin) {
		this.canadmin = canadmin;
	}

	private String googleuserid;
	private boolean canadmin;
	
	private Set trades = new HashSet(0);

	public Trader() {
	}

	public Trader(int id) {
		this.id = id;
	}

	public Trader(int id, String name, Set trades) {
		this.id = id;
		this.name = name;
		this.trades = trades;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getTrades() {
		return this.trades;
	}

	public void setTrades(Set trades) {
		this.trades = trades;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	
		  
	
}
