package com.trade.model;

// Generated Jul 7, 2014 4:30:35 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Sharedaccount generated by hbm2java
 */
@Entity
@Table(name = "sharedaccount", catalog = "trademgmt")
public class Sharedaccount implements java.io.Serializable {

	private int id;
	private Trader traderByTraderId;
	private Trader traderByShareTraderId;
	private Accounts accounts;

	public Sharedaccount() {
	}

	public Sharedaccount(int id, Trader traderByTraderId,
			Trader traderByShareTraderId, Accounts accounts) {
		this.id = id;
		this.traderByTraderId = traderByTraderId;
		this.traderByShareTraderId = traderByShareTraderId;
		this.accounts = accounts;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trader_id", nullable = false)
	public Trader getTraderByTraderId() {
		return this.traderByTraderId;
	}

	public void setTraderByTraderId(Trader traderByTraderId) {
		this.traderByTraderId = traderByTraderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "share_trader_id", nullable = false)
	public Trader getTraderByShareTraderId() {
		return this.traderByShareTraderId;
	}

	public void setTraderByShareTraderId(Trader traderByShareTraderId) {
		this.traderByShareTraderId = traderByShareTraderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_id", nullable = false)
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

}
