package com.trade.model;

// Generated Jul 2, 2014 6:03:35 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tradeattachment generated by hbm2java
 */
@Entity
@Table(name = "tradeattachment", catalog = "trademgmt")
public class Tradeattachment implements java.io.Serializable {

	private Integer id;
	private Tradeevent tradeevent;
	private String description;
	private String filename;
	private Date lastupdtdate;
	private Integer updatedby;
	private String filetype;

	public Tradeattachment() {
	}

	public Tradeattachment(Tradeevent tradeevent) {
		this.tradeevent = tradeevent;
	}

	public Tradeattachment(Tradeevent tradeevent, String description,
			String filename, Date lastupdtdate, Integer updatedby, String filetype) {
		this.tradeevent = tradeevent;
		this.description = description;
		this.filename = filename;
		this.lastupdtdate = lastupdtdate;
		this.updatedby = updatedby;
		this.filetype = filetype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tradeevent_id", nullable = false)
	public Tradeevent getTradeevent() {
		return this.tradeevent;
	}

	public void setTradeevent(Tradeevent tradeevent) {
		this.tradeevent = tradeevent;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "filename")
	public String getFilename() {
		return filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdtdate", length = 19)
	public Date getLastupdtdate() {
		return this.lastupdtdate;
	}

	public void setLastupdtdate(Date lastupdtdate) {
		this.lastupdtdate = lastupdtdate;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@Column(name = "filetype", length = 6)
	public String getFiletype() {
		return this.filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}
}
