package traderjournal.model.hibernate;
// Generated 2009/01/29 04:30:34 by Hibernate Tools 3.2.4.CR1


import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Tradeeventtype generated by hbm2java
 */
public class Tradeeventtype  extends traderjournal.model.hibernate.HibernateBaseModel implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set tradeevents = new HashSet(0);

    public Tradeeventtype() {
    }

    public Tradeeventtype(String name, Set tradeevents) {
       this.name = name;
       this.tradeevents = tradeevents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTradeevents() {
        return this.tradeevents;
    }
    
    public void setTradeevents(Set tradeevents) {
        this.tradeevents = tradeevents;
    }





public <X> X get(String property){
    if(property.equals("id")){

     return (X) getId(); 
    }
    if(property.equals("name")){

     return (X) getName(); 
    }
    if(property.equals("tradeevents")){

     return (X) getTradeevents(); 
    }
	return null;
}

public Map<String, Object> getProperties() {
		HashMap< String, Object> hm = new HashMap<String, Object>();
		
	    hm.put("id",getId() );
		
	    hm.put("name",getName() );
		
	    hm.put("tradeevents",getTradeevents() );
		return hm;
}

public Collection<String> getPropertyNames() {
		List<String> ret = new ArrayList<String>();
	    ret.add("id");
	    ret.add("name");
	    ret.add("tradeevents");
		return ret;
	}


	public <X> X remove(String property) {
		// TODO Auto-generated method stub
		return null;
	}


	public <X> X set(String property, X value) {
		    if(property.equals("id")){
		     setId(( Integer)value) ; 
		    }
		    if(property.equals("name")){
		     setName(( String)value) ; 
		    }
		    if(property.equals("tradeevents")){
		     setTradeevents(( Set)value) ; 
		    }
		
		return null;
	}


}


