package com.trade.model;

// Generated Jul 2, 2014 6:03:35 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ccy generated by hbm2java
 */
@Entity
@Table(name = "ccy", catalog = "trademgmt")
public class Ccy implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date lastupdtdate;
	private Integer updatedby;
	private Set<Accounts> accountses = new HashSet<Accounts>(0);
	private Set<Instrument> instruments = new HashSet<Instrument>(0);

	public Ccy() {
	}

	public Ccy(String name, Date lastupdtdate, Integer updatedby,
			Set<Accounts> accountses, Set<Instrument> instruments) {
		this.name = name;
		this.lastupdtdate = lastupdtdate;
		this.updatedby = updatedby;
		this.accountses = accountses;
		this.instruments = instruments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdtdate", length = 19)
	public Date getLastupdtdate() {
		return this.lastupdtdate;
	}

	public void setLastupdtdate(Date lastupdtdate) {
		this.lastupdtdate = lastupdtdate;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ccy")
	public Set<Accounts> getAccountses() {
		return this.accountses;
	}

	public void setAccountses(Set<Accounts> accountses) {
		this.accountses = accountses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ccy")
	public Set<Instrument> getInstruments() {
		return this.instruments;
	}

	public void setInstruments(Set<Instrument> instruments) {
		this.instruments = instruments;
	}

}
