package com.trade.model;

// Generated Jul 2, 2014 6:03:35 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Instrument generated by hbm2java
 */
@Entity
@Table(name = "instrument", catalog = "trademgmt")
public class Instrument implements java.io.Serializable {

	private Integer id;
	private Ccy ccy;
	private String name;
	private Date lastupdtdate;
	private Integer updatedby;
	private Set<Trade> trades = new HashSet<Trade>(0);

	public Instrument() {
	}

	public Instrument(Ccy ccy) {
		this.ccy = ccy;
	}

	public Instrument(Ccy ccy, String name, Date lastupdtdate,
			Integer updatedby, Set<Trade> trades) {
		this.ccy = ccy;
		this.name = name;
		this.lastupdtdate = lastupdtdate;
		this.updatedby = updatedby;
		this.trades = trades;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ccy_id", nullable = false)
	public Ccy getCcy() {
		return this.ccy;
	}

	public void setCcy(Ccy ccy) {
		this.ccy = ccy;
	}

	@Column(name = "name", length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdtdate", length = 19)
	public Date getLastupdtdate() {
		return this.lastupdtdate;
	}

	public void setLastupdtdate(Date lastupdtdate) {
		this.lastupdtdate = lastupdtdate;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instrument")
	public Set<Trade> getTrades() {
		return this.trades;
	}

	public void setTrades(Set<Trade> trades) {
		this.trades = trades;
	}

}
