package com.trade.model;

// Generated Jul 2, 2014 6:03:35 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tradeevent generated by hbm2java
 */
@Entity
@Table(name = "tradeevent", catalog = "trademgmt")
public class Tradeevent implements java.io.Serializable {

	private Integer id;
	private Tradeeventtype tradeeventtype;
	private Trade trade;
	private Date eventdate;
	private String description;
	private Integer eventorder;
	private BigDecimal newvalue;
	private Date lastupdtdate;
	private Integer updatedby;
	private Set<Tradeattachment> tradeattachments = new HashSet<Tradeattachment>(
			0);

	public Tradeevent() {
	}

	public Tradeevent(Tradeeventtype tradeeventtype, Trade trade) {
		this.tradeeventtype = tradeeventtype;
		this.trade = trade;
	}

	public Tradeevent(Tradeeventtype tradeeventtype, Trade trade,
			Date eventdate, String description, Integer eventorder,
			BigDecimal newvalue, Date lastupdtdate, Integer updatedby,
			Set<Tradeattachment> tradeattachments) {
		this.tradeeventtype = tradeeventtype;
		this.trade = trade;
		this.eventdate = eventdate;
		this.description = description;
		this.eventorder = eventorder;
		this.newvalue = newvalue;
		this.lastupdtdate = lastupdtdate;
		this.updatedby = updatedby;
		this.tradeattachments = tradeattachments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "tradeeventtype_id", nullable = false)
	public Tradeeventtype getTradeeventtype() {
		return this.tradeeventtype;
	}

	public void setTradeeventtype(Tradeeventtype tradeeventtype) {
		this.tradeeventtype = tradeeventtype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "trade_id", nullable = false)
	public Trade getTrade() {
		return this.trade;
	}

	public void setTrade(Trade trade) {
		this.trade = trade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "eventdate", length = 19)
	public Date getEventdate() {
		return this.eventdate;
	}

	public void setEventdate(Date eventdate) {
		this.eventdate = eventdate;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "eventorder")
	public Integer getEventorder() {
		return this.eventorder;
	}

	public void setEventorder(Integer eventorder) {
		this.eventorder = eventorder;
	}

	@Column(name = "newvalue", precision = 7)
	public BigDecimal getNewvalue() {
		return this.newvalue;
	}

	public void setNewvalue(BigDecimal newvalue) {
		this.newvalue = newvalue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "lastupdtdate", length = 19)
	public Date getLastupdtdate() {
		return this.lastupdtdate;
	}

	public void setLastupdtdate(Date lastupdtdate) {
		this.lastupdtdate = lastupdtdate;
	}

	@Column(name = "updatedby")
	public Integer getUpdatedby() {
		return this.updatedby;
	}

	public void setUpdatedby(Integer updatedby) {
		this.updatedby = updatedby;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tradeevent")
	public Set<Tradeattachment> getTradeattachments() {
		return this.tradeattachments;
	}

	public void setTradeattachments(Set<Tradeattachment> tradeattachments) {
		this.tradeattachments = tradeattachments;
	}

}
