package traderjournal.model.hibernate;

// Generated 2008/06/05 03:03:06 by Hibernate Tools 3.2.1.GA

/**
 * Tradeeventimage generated by hbm2java
 */
public class Tradeeventimage implements java.io.Serializable {

	private int id;
	private Tradeevent tradeevent;
	private String description;
	private byte[] img;

	public Tradeeventimage() {
	}

	public Tradeeventimage(int id) {
		this.id = id;
	}

	public Tradeeventimage(int id, Tradeevent tradeevent, String description,
			byte[] img) {
		this.id = id;
		this.tradeevent = tradeevent;
		this.description = description;
		this.img = img;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Tradeevent getTradeevent() {
		return this.tradeevent;
	}

	public void setTradeevent(Tradeevent tradeevent) {
		this.tradeevent = tradeevent;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getImg() {
		return this.img;
	}

	public void setImg(byte[] img) {
		this.img = img;
	}

}
