package traderjournal.model.hibernate;

// Generated 2008/05/27 01:45:17 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private int id;
	private Ccy ccy;
	private String name;
	private double balance;
	private Set<Trade> trades = new HashSet<Trade>(0);

	public Account() {
	}

	public Account(int id, String name, double balance) {
		this.id = id;
		this.name = name;
		this.balance = balance;
	}

	public Account(int id, Ccy ccy, String name, double balance,
			Set<Trade> trades) {
		this.id = id;
		this.ccy = ccy;
		this.name = name;
		this.balance = balance;
		this.trades = trades;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Ccy getCcy() {
		return this.ccy;
	}

	public void setCcy(Ccy ccy) {
		this.ccy = ccy;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getBalance() {
		return this.balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	public Set<Trade> getTrades() {
		return this.trades;
	}

	public void setTrades(Set<Trade> trades) {
		this.trades = trades;
	}

}
