package traderjournal.model.hibernate;

// Generated 2008/05/26 04:30:45 by Hibernate Tools 3.2.1.GA

import java.util.Arrays;

/**
 * TradeeventimageId generated by hbm2java
 */
public class TradeeventimageId implements java.io.Serializable {

	private Integer id;
	private Integer eventId;
	private String description;
	private byte[] img2;

	public TradeeventimageId() {
	}

	public TradeeventimageId(Integer id, Integer eventId, String description,
			byte[] img2) {
		this.id = id;
		this.eventId = eventId;
		this.description = description;
		this.img2 = img2;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getEventId() {
		return this.eventId;
	}

	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public byte[] getImg2() {
		return this.img2;
	}

	public void setImg2(byte[] img2) {
		this.img2 = img2;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TradeeventimageId))
			return false;
		TradeeventimageId castOther = (TradeeventimageId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getEventId() == castOther.getEventId()) || (this
						.getEventId() != null
						&& castOther.getEventId() != null && this.getEventId()
						.equals(castOther.getEventId())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getImg2() == castOther.getImg2()) || (this.getImg2() != null
						&& castOther.getImg2() != null && Arrays.equals(this
						.getImg2(), castOther.getImg2())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getEventId() == null ? 0 : this.getEventId().hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37 * result
				+ (getImg2() == null ? 0 : Arrays.hashCode(this.getImg2()));
		return result;
	}

}
