package traderjournal.model.hibernate;
// Generated 2009/01/29 04:30:34 by Hibernate Tools 3.2.4.CR1


import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Tradeeventimage generated by hbm2java
 */
public class Tradeeventimage  extends traderjournal.model.hibernate.HibernateBaseModel implements java.io.Serializable {


     private Integer id;
     private Tradeevent tradeevent;
     private String description;
     private byte[] img;

    public Tradeeventimage() {
    }

    public Tradeeventimage(Tradeevent tradeevent, String description, byte[] img) {
       this.tradeevent = tradeevent;
       this.description = description;
       this.img = img;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Tradeevent getTradeevent() {
        return this.tradeevent;
    }
    
    public void setTradeevent(Tradeevent tradeevent) {
        this.tradeevent = tradeevent;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public byte[] getImg() {
        return this.img;
    }
    
    public void setImg(byte[] img) {
        this.img = img;
    }





public <X> X get(String property){
    if(property.equals("id")){

     return (X) getId(); 
    }
    if(property.equals("tradeevent")){

     return (X) getTradeevent(); 
    }
    if(property.equals("description")){

     return (X) getDescription(); 
    }
    if(property.equals("img")){

     return (X) getImg(); 
    }
	return null;
}

public Map<String, Object> getProperties() {
		HashMap< String, Object> hm = new HashMap<String, Object>();
		
	    hm.put("id",getId() );
		
	    hm.put("tradeevent",getTradeevent() );
		
	    hm.put("description",getDescription() );
		
	    hm.put("img",getImg() );
		return hm;
}

public Collection<String> getPropertyNames() {
		List<String> ret = new ArrayList<String>();
	    ret.add("id");
	    ret.add("tradeevent");
	    ret.add("description");
	    ret.add("img");
		return ret;
	}


	public <X> X remove(String property) {
		// TODO Auto-generated method stub
		return null;
	}


	public <X> X set(String property, X value) {
		    if(property.equals("id")){
		     setId(( Integer)value) ; 
		    }
		    if(property.equals("tradeevent")){
		     setTradeevent(( Tradeevent)value) ; 
		    }
		    if(property.equals("description")){
		     setDescription(( String)value) ; 
		    }
		    if(property.equals("img")){
		     setImg(( byte[])value) ; 
		    }
		
		return null;
	}


}


