package traderjournal.model.hibernate;

// Generated 2008/05/26 12:00:37 by Hibernate Tools 3.2.1.GA

/**
 * TradeeventtypeId generated by hbm2java
 */
public class TradeeventtypeId implements java.io.Serializable {

	private Integer id;
	private String name;

	public TradeeventtypeId() {
	}

	public TradeeventtypeId(Integer id, String name) {
		this.id = id;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TradeeventtypeId))
			return false;
		TradeeventtypeId castOther = (TradeeventtypeId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
