package traderjournal.model.hibernate;

// Generated 2008/05/26 12:00:37 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * TradeeventId generated by hbm2java
 */
public class TradeeventId implements java.io.Serializable {

	private Integer id;
	private Date eventDate;
	private Integer eventTypeId;
	private String description;
	private Integer eventorder;
	private Integer tradeid;

	public TradeeventId() {
	}

	public TradeeventId(Integer id, Date eventDate, Integer eventTypeId,
			String description, Integer eventorder, Integer tradeid) {
		this.id = id;
		this.eventDate = eventDate;
		this.eventTypeId = eventTypeId;
		this.description = description;
		this.eventorder = eventorder;
		this.tradeid = tradeid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getEventDate() {
		return this.eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}

	public Integer getEventTypeId() {
		return this.eventTypeId;
	}

	public void setEventTypeId(Integer eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getEventorder() {
		return this.eventorder;
	}

	public void setEventorder(Integer eventorder) {
		this.eventorder = eventorder;
	}

	public Integer getTradeid() {
		return this.tradeid;
	}

	public void setTradeid(Integer tradeid) {
		this.tradeid = tradeid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TradeeventId))
			return false;
		TradeeventId castOther = (TradeeventId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getEventDate() == castOther.getEventDate()) || (this
						.getEventDate() != null
						&& castOther.getEventDate() != null && this
						.getEventDate().equals(castOther.getEventDate())))
				&& ((this.getEventTypeId() == castOther.getEventTypeId()) || (this
						.getEventTypeId() != null
						&& castOther.getEventTypeId() != null && this
						.getEventTypeId().equals(castOther.getEventTypeId())))
				&& ((this.getDescription() == castOther.getDescription()) || (this
						.getDescription() != null
						&& castOther.getDescription() != null && this
						.getDescription().equals(castOther.getDescription())))
				&& ((this.getEventorder() == castOther.getEventorder()) || (this
						.getEventorder() != null
						&& castOther.getEventorder() != null && this
						.getEventorder().equals(castOther.getEventorder())))
				&& ((this.getTradeid() == castOther.getTradeid()) || (this
						.getTradeid() != null
						&& castOther.getTradeid() != null && this.getTradeid()
						.equals(castOther.getTradeid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getEventDate() == null ? 0 : this.getEventDate().hashCode());
		result = 37
				* result
				+ (getEventTypeId() == null ? 0 : this.getEventTypeId()
						.hashCode());
		result = 37
				* result
				+ (getDescription() == null ? 0 : this.getDescription()
						.hashCode());
		result = 37
				* result
				+ (getEventorder() == null ? 0 : this.getEventorder()
						.hashCode());
		result = 37 * result
				+ (getTradeid() == null ? 0 : this.getTradeid().hashCode());
		return result;
	}

}
