package traderjournal.model.hibernate;

// Generated 2008/05/26 12:00:37 by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * TradeId generated by hbm2java
 */
public class TradeId implements java.io.Serializable {

	private Integer id;
	private Date openTradeDate;
	private Double openprice;
	private Date closeTradeDate;
	private Double closeprice;
	private Double stoploss;
	private Double tp;
	private Integer qty;
	private String instrument;
	private Double entrycoms;
	private Double exitcoms;
	private Double entryfee;
	private Double exitfee;
	private Double pl;
	private String reference;
	private Double carrycost;

	public TradeId() {
	}

	public TradeId(Integer id, Date openTradeDate, Double openprice,
			Date closeTradeDate, Double closeprice, Double stoploss, Double tp,
			Integer qty, String instrument, Double entrycoms, Double exitcoms,
			Double entryfee, Double exitfee, Double pl, String reference,
			Double carrycost) {
		this.id = id;
		this.openTradeDate = openTradeDate;
		this.openprice = openprice;
		this.closeTradeDate = closeTradeDate;
		this.closeprice = closeprice;
		this.stoploss = stoploss;
		this.tp = tp;
		this.qty = qty;
		this.instrument = instrument;
		this.entrycoms = entrycoms;
		this.exitcoms = exitcoms;
		this.entryfee = entryfee;
		this.exitfee = exitfee;
		this.pl = pl;
		this.reference = reference;
		this.carrycost = carrycost;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getOpenTradeDate() {
		return this.openTradeDate;
	}

	public void setOpenTradeDate(Date openTradeDate) {
		this.openTradeDate = openTradeDate;
	}

	public Double getOpenprice() {
		return this.openprice;
	}

	public void setOpenprice(Double openprice) {
		this.openprice = openprice;
	}

	public Date getCloseTradeDate() {
		return this.closeTradeDate;
	}

	public void setCloseTradeDate(Date closeTradeDate) {
		this.closeTradeDate = closeTradeDate;
	}

	public Double getCloseprice() {
		return this.closeprice;
	}

	public void setCloseprice(Double closeprice) {
		this.closeprice = closeprice;
	}

	public Double getStoploss() {
		return this.stoploss;
	}

	public void setStoploss(Double stoploss) {
		this.stoploss = stoploss;
	}

	public Double getTp() {
		return this.tp;
	}

	public void setTp(Double tp) {
		this.tp = tp;
	}

	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	public String getInstrument() {
		return this.instrument;
	}

	public void setInstrument(String instrument) {
		this.instrument = instrument;
	}

	public Double getEntrycoms() {
		return this.entrycoms;
	}

	public void setEntrycoms(Double entrycoms) {
		this.entrycoms = entrycoms;
	}

	public Double getExitcoms() {
		return this.exitcoms;
	}

	public void setExitcoms(Double exitcoms) {
		this.exitcoms = exitcoms;
	}

	public Double getEntryfee() {
		return this.entryfee;
	}

	public void setEntryfee(Double entryfee) {
		this.entryfee = entryfee;
	}

	public Double getExitfee() {
		return this.exitfee;
	}

	public void setExitfee(Double exitfee) {
		this.exitfee = exitfee;
	}

	public Double getPl() {
		return this.pl;
	}

	public void setPl(Double pl) {
		this.pl = pl;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public Double getCarrycost() {
		return this.carrycost;
	}

	public void setCarrycost(Double carrycost) {
		this.carrycost = carrycost;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TradeId))
			return false;
		TradeId castOther = (TradeId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getOpenTradeDate() == castOther.getOpenTradeDate()) || (this
						.getOpenTradeDate() != null
						&& castOther.getOpenTradeDate() != null && this
						.getOpenTradeDate()
						.equals(castOther.getOpenTradeDate())))
				&& ((this.getOpenprice() == castOther.getOpenprice()) || (this
						.getOpenprice() != null
						&& castOther.getOpenprice() != null && this
						.getOpenprice().equals(castOther.getOpenprice())))
				&& ((this.getCloseTradeDate() == castOther.getCloseTradeDate()) || (this
						.getCloseTradeDate() != null
						&& castOther.getCloseTradeDate() != null && this
						.getCloseTradeDate().equals(
								castOther.getCloseTradeDate())))
				&& ((this.getCloseprice() == castOther.getCloseprice()) || (this
						.getCloseprice() != null
						&& castOther.getCloseprice() != null && this
						.getCloseprice().equals(castOther.getCloseprice())))
				&& ((this.getStoploss() == castOther.getStoploss()) || (this
						.getStoploss() != null
						&& castOther.getStoploss() != null && this
						.getStoploss().equals(castOther.getStoploss())))
				&& ((this.getTp() == castOther.getTp()) || (this.getTp() != null
						&& castOther.getTp() != null && this.getTp().equals(
						castOther.getTp())))
				&& ((this.getQty() == castOther.getQty()) || (this.getQty() != null
						&& castOther.getQty() != null && this.getQty().equals(
						castOther.getQty())))
				&& ((this.getInstrument() == castOther.getInstrument()) || (this
						.getInstrument() != null
						&& castOther.getInstrument() != null && this
						.getInstrument().equals(castOther.getInstrument())))
				&& ((this.getEntrycoms() == castOther.getEntrycoms()) || (this
						.getEntrycoms() != null
						&& castOther.getEntrycoms() != null && this
						.getEntrycoms().equals(castOther.getEntrycoms())))
				&& ((this.getExitcoms() == castOther.getExitcoms()) || (this
						.getExitcoms() != null
						&& castOther.getExitcoms() != null && this
						.getExitcoms().equals(castOther.getExitcoms())))
				&& ((this.getEntryfee() == castOther.getEntryfee()) || (this
						.getEntryfee() != null
						&& castOther.getEntryfee() != null && this
						.getEntryfee().equals(castOther.getEntryfee())))
				&& ((this.getExitfee() == castOther.getExitfee()) || (this
						.getExitfee() != null
						&& castOther.getExitfee() != null && this.getExitfee()
						.equals(castOther.getExitfee())))
				&& ((this.getPl() == castOther.getPl()) || (this.getPl() != null
						&& castOther.getPl() != null && this.getPl().equals(
						castOther.getPl())))
				&& ((this.getReference() == castOther.getReference()) || (this
						.getReference() != null
						&& castOther.getReference() != null && this
						.getReference().equals(castOther.getReference())))
				&& ((this.getCarrycost() == castOther.getCarrycost()) || (this
						.getCarrycost() != null
						&& castOther.getCarrycost() != null && this
						.getCarrycost().equals(castOther.getCarrycost())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getOpenTradeDate() == null ? 0 : this.getOpenTradeDate()
						.hashCode());
		result = 37 * result
				+ (getOpenprice() == null ? 0 : this.getOpenprice().hashCode());
		result = 37
				* result
				+ (getCloseTradeDate() == null ? 0 : this.getCloseTradeDate()
						.hashCode());
		result = 37
				* result
				+ (getCloseprice() == null ? 0 : this.getCloseprice()
						.hashCode());
		result = 37 * result
				+ (getStoploss() == null ? 0 : this.getStoploss().hashCode());
		result = 37 * result + (getTp() == null ? 0 : this.getTp().hashCode());
		result = 37 * result
				+ (getQty() == null ? 0 : this.getQty().hashCode());
		result = 37
				* result
				+ (getInstrument() == null ? 0 : this.getInstrument()
						.hashCode());
		result = 37 * result
				+ (getEntrycoms() == null ? 0 : this.getEntrycoms().hashCode());
		result = 37 * result
				+ (getExitcoms() == null ? 0 : this.getExitcoms().hashCode());
		result = 37 * result
				+ (getEntryfee() == null ? 0 : this.getEntryfee().hashCode());
		result = 37 * result
				+ (getExitfee() == null ? 0 : this.getExitfee().hashCode());
		result = 37 * result + (getPl() == null ? 0 : this.getPl().hashCode());
		result = 37 * result
				+ (getReference() == null ? 0 : this.getReference().hashCode());
		result = 37 * result
				+ (getCarrycost() == null ? 0 : this.getCarrycost().hashCode());
		return result;
	}

}
