package traderjournal.model.hibernate;

// Generated 2008/05/26 04:30:45 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * TransactionType generated by hbm2java
 */
public class TransactionType implements java.io.Serializable {

	private int id;
	private String type;
	private Set<Transaction> transactions = new HashSet<Transaction>(0);

	public TransactionType() {
	}

	public TransactionType(int id, String type) {
		this.id = id;
		this.type = type;
	}

	public TransactionType(int id, String type, Set<Transaction> transactions) {
		this.id = id;
		this.type = type;
		this.transactions = transactions;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set<Transaction> getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set<Transaction> transactions) {
		this.transactions = transactions;
	}

}
